name: Node Product API Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-sast:
    name: 0. SAST (Segurança Node.js)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Auditoria de segurança
        run: npm audit --audit-level=high

  environment-setup:
    name: 1. Setup & Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: npm

      - name: Instalar dependências
        run: npm ci

  code-linting:
    name: 2. Code Quality (ESLint)
    needs: environment-setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar Linter
        run: npm run lint

  unit-tests:
    name: 3. Automation Tests (Jest)
    needs: environment-setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar Testes
        run: npm test